name: auto commit

on: issue_comment

jobs:
  autocommit:
  
    if: 
      github.event.comment.author_association == 'OWNER' && 
      github.event.comment.body == 'ok' &&
      github.event.issue.labels[0].name == 'autocommit'
      
    runs-on: ubuntu-latest

    steps:
      
      # check out main branch
      - name: checkout
        uses: actions/checkout@main

      # use node
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      # install dependencies
      - name: Install dependencies 
        run: npm install
        
      # run script
      - name: update data
        run: npm run issues ${{github.event.issue.body}}
      
      # config git
      - name: config git
        run: git config --global user.email "aierklk@gmail.com"&&git config --global user.name "aierklk"
        
      # commit
      - name: commit
        run: git commit -am "auto update list" 
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      # push
      - name: push  
        run: git push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
